"""user table - add default value for isPremium

Revision ID: 19234fcc0335
Revises: b6cc97ab899c
Create Date: 2022-01-31 13:08:23.190087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19234fcc0335'
down_revision = 'b6cc97ab899c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
