"""add one to many relationship category to subcategories

Revision ID: 2962b502d8fb
Revises: c7614a3ee61c
Create Date: 2022-02-09 15:41:43.515946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2962b502d8fb'
down_revision = 'c7614a3ee61c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
