"""autogenerate the transactions table

Revision ID: 399ec9be4d39
Revises: 5e71d778fb69
Create Date: 2022-01-29 18:52:17.116348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '399ec9be4d39'
down_revision = '5e71d778fb69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
