"""user table - add new column isPremiums

Revision ID: 4b4203fd7941
Revises: eded629a2fad
Create Date: 2022-01-31 13:43:14.634320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b4203fd7941'
down_revision = 'eded629a2fad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_premium')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_premium', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
