"""make transaction_type not nullable

Revision ID: 5e71d778fb69
Revises: 84aeeb05a85e
Create Date: 2022-01-29 18:50:20.447662

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5e71d778fb69'
down_revision = '84aeeb05a85e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'transaction_type',
               existing_type=postgresql.ENUM('Income', 'Expense', name='transaction_type'),
               nullable=False)
    op.alter_column('subcategories', 'transaction_type',
               existing_type=postgresql.ENUM('Income', 'Expense', name='transaction_type'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subcategories', 'transaction_type',
               existing_type=postgresql.ENUM('Income', 'Expense', name='transaction_type'),
               nullable=True)
    op.alter_column('categories', 'transaction_type',
               existing_type=postgresql.ENUM('Income', 'Expense', name='transaction_type'),
               nullable=True)
    # ### end Alembic commands ###
