"""user table - add new column isPremium

Revision ID: a2ecccf23258
Revises: 4b4203fd7941
Create Date: 2022-01-31 13:45:29.128676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2ecccf23258'
down_revision = '4b4203fd7941'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_premium', sa.Boolean(), server_default='false', nullable=False))
    op.drop_column('users', 'is_premiums')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_premiums', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_column('users', 'is_premium')
    # ### end Alembic commands ###
