"""update the user table to accept passwords

Revision ID: b6cc97ab899c
Revises: ceaa233fe036
Create Date: 2022-01-31 13:05:34.534375

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b6cc97ab899c'
down_revision = 'ceaa233fe036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'transaction_types')
    op.add_column('users', sa.Column('password', sa.String(), nullable=False))
    op.alter_column('users', 'access_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'access_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'password')
    op.add_column('transactions', sa.Column('transaction_types', postgresql.ENUM('Income', 'Expense', name='transaction_type'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
