"""user table - add default value for isPremium

Revision ID: bbb535dac2d9
Revises: 19234fcc0335
Create Date: 2022-01-31 13:11:18.685063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbb535dac2d9'
down_revision = '19234fcc0335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
