"""category - update transactype enum values

Revision ID: c7614a3ee61c
Revises: a2ecccf23258
Create Date: 2022-02-09 12:46:03.936495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7614a3ee61c'
down_revision = 'a2ecccf23258'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
