"""update the transaction table

Revision ID: ceaa233fe036
Revises: 0129dbd812d2
Create Date: 2022-01-29 19:06:28.796228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceaa233fe036'
down_revision = '0129dbd812d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('transaction_types', sa.Enum('Income', 'Expense', name='transaction_type'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'transaction_types')
    # ### end Alembic commands ###
