"""user table - add new column isPremiums

Revision ID: eded629a2fad
Revises: bbb535dac2d9
Create Date: 2022-01-31 13:42:00.244356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eded629a2fad'
down_revision = 'bbb535dac2d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_premiums', sa.Boolean(), server_default='True', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_premiums')
    # ### end Alembic commands ###
